from django.urls import path

from main_app.EditResultView import EditResultView

from . import hod_views, staff_views, booking_views, views

urlpatterns = [
    path("", views.landing_page, name="landing_page"),
    path("login/", views.login_page, name="login_page"),
    path("get_trips", views.get_trips, name='get_trips'),
    path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("logout_user/", views.logout_user, name='user_logout'),
    path("admin/home/", hod_views.admin_home, name='admin_home'),
    path("staff/add", hod_views.add_staff, name='add_staff'),
    path("role/add", hod_views.add_role, name='add_role'),
    path("send_staff_notification/", hod_views.send_staff_notification,
         name='send_staff_notification'),
    path("add_Season/", hod_views.add_Season, name='add_Season'),
    path("admin_notify_staff", hod_views.admin_notify_staff,
         name='admin_notify_staff'),
    path("admin_view_profile", hod_views.admin_view_profile,
         name='admin_view_profile'),
    path("check_email_availability", hod_views.check_email_availability,
         name="check_email_availability"),
    path("Season/manage/", hod_views.manage_Season, name='manage_Season'),
    path("Season/edit/<int:Season_id>",
         hod_views.edit_Season, name='edit_Season'),
    path("booking/view/feedback/", hod_views.booking_feedback_message,
         name="booking_feedback_message",),
    path("staff/view/feedback/", hod_views.staff_feedback_message,
         name="staff_feedback_message",),
    path("staff/view/leave/", hod_views.view_staff_leave, name="view_staff_leave",),
    path("trips/fetch/", hod_views.get_admin_trips,
         name='get_admin_trips'),
    path("booking/add/", hod_views.add_booking, name='add_booking'),
    path("Car/add/", hod_views.add_Car, name='add_Car'),
    path("itinerary/add/", hod_views.add_itinerary, name='add_itinerary'),
    path("staff/manage/", hod_views.manage_staff, name='manage_staff'),
    path("booking/manage/", hod_views.manage_booking, name='manage_booking'),
    path("role/manage/", hod_views.manage_role, name='manage_role'),
    path("Car/manage/", hod_views.manage_Car, name='manage_Car'),
    path("itinerary/manage/", hod_views.manage_itinerary, name='manage_itinerary'),
    path("staff/edit/<int:staff_id>", hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:staff_id>",
         hod_views.delete_staff, name='delete_staff'),

    path("role/delete/<int:role_id>",
         hod_views.delete_role, name='delete_role'),

    path("Car/delete/<int:Car_id>",
         hod_views.delete_Car, name='delete_Car'),

    path("itinerary/delete/<int:itinerary_id>",
         hod_views.delete_itinerary, name='delete_itinerary'),

    path("Season/delete/<int:Season_id>",
         hod_views.delete_Season, name='delete_Season'),

    path("booking/delete/<int:booking_id>",
         hod_views.delete_booking, name='delete_booking'),
    path("booking/edit/<int:booking_id>",
         hod_views.edit_booking, name='edit_booking'),
    path("role/edit/<int:role_id>",
         hod_views.edit_role, name='edit_role'),
    path("itinerary/edit/<int:itinerary_id>",
         hod_views.edit_itinerary, name='edit_itinerary'),
    path("Car/edit/<int:Car_id>",
         hod_views.edit_Car, name='edit_Car'),




    # Staff
    path("staff/home/", staff_views.staff_home, name='staff_home'),
    path("staff/apply/leave/", staff_views.staff_apply_leave,
         name='staff_apply_leave'),
    path("staff/feedback/", staff_views.staff_feedback, name='staff_feedback'),
    path("staff/view/profile/", staff_views.staff_view_profile,
         name='staff_view_profile'),
    path("staff/trips/take/", staff_views.staff_take_trips,
         name='staff_take_trips'),
    path("staff/trips/update/", staff_views.staff_update_trips,
         name='staff_update_trips'),
    path("staff/get_bookings/", staff_views.get_bookings, name='get_bookings'),
    path("staff/trips/fetch/", staff_views.get_booking_trips,
         name='get_booking_trips'),
    path("staff/trips/save/",
         staff_views.save_trips, name='save_trips'),
    path("staff/trips/update/",
         staff_views.update_trips, name='update_trips'),
    path("staff/fcmtoken/", staff_views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/", staff_views.staff_view_notification,
         name="staff_view_notification"),
    path("staff/result/add/", staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/", EditResultView.as_view(),
         name='edit_booking_result'),
    path('staff/result/fetch/', staff_views.fetch_booking_result,
         name='fetch_booking_result'),


    # booking
    path("booking/home/", booking_views.booking_home, name='booking_home'),
    path("booking/view/trips/", booking_views.booking_view_trips,
         name='booking_view_trips'),
    path("booking/apply/leave/", booking_views.booking_apply_leave,
         name='booking_apply_leave'),
    path("booking/feedback/", booking_views.booking_feedback,
         name='booking_feedback'),
    path("booking/view/profile/", booking_views.booking_view_profile,
         name='booking_view_profile'),
    path("booking/fcmtoken/", booking_views.booking_fcmtoken,
         name='booking_fcmtoken'),
    path("booking/view/notification/", booking_views.booking_view_notification,
         name="booking_view_notification"),
    path('booking/view/result/', booking_views.booking_view_result,
         name='booking_view_result'),

]
