from django.urls import path

from main_app.EditResultView import EditResultView

from . import hod_views, staff_views, inquiry_views, views

urlpatterns = [
    path("", views.login_page, name='login_page'),
    path("get_attendance", views.get_attendance, name='get_attendance'),
    path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("logout_user/", views.logout_user, name='user_logout'),
    path("admin/home/", hod_views.admin_home, name='admin_home'),
    path("staff/add", hod_views.add_staff, name='add_staff'),
    path("role/add", hod_views.add_role, name='add_role'),
    path("send_Inquiry_notification/", hod_views.send_Inquiry_notification,
         name='send_Inquiry_notification'),
    path("send_staff_notification/", hod_views.send_staff_notification,
         name='send_staff_notification'),
    path("add_Season/", hod_views.add_Season, name='add_Season'),
    path("admin_notify_Inquiry", hod_views.admin_notify_Inquiry,
         name='admin_notify_Inquiry'),
    path("admin_notify_staff", hod_views.admin_notify_staff,
         name='admin_notify_staff'),
    path("admin_view_profile", hod_views.admin_view_profile,
         name='admin_view_profile'),
    path("check_email_availability", hod_views.check_email_availability,
         name="check_email_availability"),
    path("Season/manage/", hod_views.manage_Season, name='manage_Season'),
    path("Season/edit/<int:Season_id>",
         hod_views.edit_Season, name='edit_Season'),
    path("Inquiry/view/feedback/", hod_views.Inquiry_feedback_message,
         name="Inquiry_feedback_message",),
    path("staff/view/feedback/", hod_views.staff_feedback_message,
         name="staff_feedback_message",),
    path("Inquiry/view/leave/", hod_views.view_Inquiry_leave,
         name="view_Inquiry_leave",),
    path("staff/view/leave/", hod_views.view_staff_leave, name="view_staff_leave",),
    path("attendance/view/", hod_views.admin_view_attendance,
         name="admin_view_attendance",),
    path("attendance/fetch/", hod_views.get_admin_attendance,
         name='get_admin_attendance'),
    path("Inquiry/add/", hod_views.add_Inquiry, name='add_Inquiry'),
    path("Car/add/", hod_views.add_Car, name='add_Car'),
    path("staff/manage/", hod_views.manage_staff, name='manage_staff'),
    path("Inquiry/manage/", hod_views.manage_Inquiry, name='manage_Inquiry'),
    path("role/manage/", hod_views.manage_role, name='manage_role'),
    path("Car/manage/", hod_views.manage_Car, name='manage_Car'),
    path("staff/edit/<int:staff_id>", hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:staff_id>",
         hod_views.delete_staff, name='delete_staff'),

    path("role/delete/<int:role_id>",
         hod_views.delete_role, name='delete_role'),

    path("Car/delete/<int:Car_id>",
         hod_views.delete_Car, name='delete_Car'),

    path("Season/delete/<int:Season_id>",
         hod_views.delete_Season, name='delete_Season'),

    path("Inquiry/delete/<int:Inquiry_id>",
         hod_views.delete_Inquiry, name='delete_Inquiry'),
    path("Inquiry/edit/<int:Inquiry_id>",
         hod_views.edit_Inquiry, name='edit_Inquiry'),
    path("role/edit/<int:role_id>",
         hod_views.edit_role, name='edit_role'),
    path("Car/edit/<int:Car_id>",
         hod_views.edit_Car, name='edit_Car'),


    # Staff
    path("staff/home/", staff_views.staff_home, name='staff_home'),
    path("staff/apply/leave/", staff_views.staff_apply_leave,
         name='staff_apply_leave'),
    path("staff/feedback/", staff_views.staff_feedback, name='staff_feedback'),
    path("staff/view/profile/", staff_views.staff_view_profile,
         name='staff_view_profile'),
    path("staff/attendance/take/", staff_views.staff_take_attendance,
         name='staff_take_attendance'),
    path("staff/attendance/update/", staff_views.staff_update_attendance,
         name='staff_update_attendance'),
    path("staff/get_inquiries/", staff_views.get_inquiries, name='get_inquiries'),
    path("staff/attendance/fetch/", staff_views.get_Inquiry_attendance,
         name='get_Inquiry_attendance'),
    path("staff/attendance/save/",
         staff_views.save_attendance, name='save_attendance'),
    path("staff/attendance/update/",
         staff_views.update_attendance, name='update_attendance'),
    path("staff/fcmtoken/", staff_views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/", staff_views.staff_view_notification,
         name="staff_view_notification"),
    path("staff/result/add/", staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/", EditResultView.as_view(),
         name='edit_Inquiry_result'),
    path('staff/result/fetch/', staff_views.fetch_Inquiry_result,
         name='fetch_Inquiry_result'),



    # Inquiry
    path("Inquiry/home/", inquiry_views.Inquiry_home, name='Inquiry_home'),
    path("Inquiry/view/attendance/", inquiry_views.Inquiry_view_attendance,
         name='Inquiry_view_attendance'),
    path("Inquiry/apply/leave/", inquiry_views.Inquiry_apply_leave,
         name='Inquiry_apply_leave'),
    path("Inquiry/feedback/", inquiry_views.Inquiry_feedback,
         name='Inquiry_feedback'),
    path("Inquiry/view/profile/", inquiry_views.Inquiry_view_profile,
         name='Inquiry_view_profile'),
    path("Inquiry/fcmtoken/", inquiry_views.Inquiry_fcmtoken,
         name='Inquiry_fcmtoken'),
    path("Inquiry/view/notification/", inquiry_views.Inquiry_view_notification,
         name="Inquiry_view_notification"),
    path('Inquiry/view/result/', inquiry_views.Inquiry_view_result,
         name='Inquiry_view_result'),

]
